### ISSUE TITLE
Can't handle null fields

### ISSUE THREAD

**Issue by sischnei** [karimayachi/knockout-firestore#2]
Hi,

upon trying out the library, I noticed that it seems to be unable to handle null fields.

    Uncaught TypeError: Cannot read property 'toDate' of null
      at explodeObject (knockout.firestore.js:459)
      at knockout.firestore.js:392
      at Array.forEach (<anonymous>)
      at Object.next (knockout.firestore.js:372)
      at next (firebase.js:1)
      at firebase.js:1

It fails for this object and the description property:
![image](https://user-images.githubusercontent.com/1112685/48938425-73bc4180-ef11-11e8-818f-0150853cd2eb.png)

**Comment by karimayachi** [comment]
Hi @sischnei,

You're right. This will be fixed in 1.1.0, but as I'm not working on Firebase-related projects at the moment, it could be a while before that version will be released.
Therefore I made a small patch on the master-branch. Should work now.

Regards,
Karim
